all:
  vars:
    ansible_user: "{{ grantsible_user }}"
    ansible_port: 22
    host_url: https://grantsdb.epfl.ch/
    ansible_python_interpreter: /opt/rh/rh-python36/root/usr/bin/python3
    inventory_environment: prod
    host_url: https://grantsdb.epfl.ch/
    application_deployment_path: /www/grantsdb/web
  hosts:
    grantsprod-1:
      ansible_host: darsrv1.epfl.ch
    grantsprod-2:
      ansible_host: darsrv3.epfl.ch
