- name: Register current hostname
  ansible.builtin.shell: hostname
  register: current_hostname

- name: Show hostname
  debug:
    msg: "{{ current_hostname.stdout }} || {{ ansible_host }} || {{ inventory_hostname }}"

- name: print inventory_hostname
  ansible.builtin.debug:
    var: inventory_hostname
